### ISSUE TITLE
Naming convention and consistency

### ISSUE THREAD

**Issue by biagiodistefano** [Develawpers/OpenCodingLibraryForLawyers#1]
- Rename directory `How_to_calculate_speeding_fines_under_Italian_law` to `speeding_fines_ita` or similar
- Ensure consistency between directory and file naming. E.g., dir `speeding_fines_ita` -> filename from `speed_limit.py` to `speeding_fines_ita.py`, or, if it's the only file in the directory `main.py` is ok, too.
- Rename Wiki.tx to README.md and rewrite in markdown.

Once everything is done, commit with comment "fix #1" to automagically close this issue.

**Comment by SimoneCedrola** [comment]
1) I am not able to rename directory
2) Done
3) Done

**Comment by SimoneCedrola** [comment]
fix #1
